<html>
    <?php
    require_once("../controller/connexion.php");
    $idIngred=$_POST['IdIngred'];
    $frais=$_POST['NomIngred'];
    $NomIngred=$_POST['NomIngred'];
    $NomIngred=$_POST['NomIngred'];
    $NomIngred=$_POST['NomIngred'];
    $NomIngred=$_POST['NomIngred'];
    $NomIngred=$_POST['NomIngred'];
    $NomIngred=$_POST['NomIngred'];
    $NomIngred=$_POST['NomIngred'];
    $NomIngred=$_POST['NomIngred'];
    ?>
</html>